# Generated by Django 4.2.7 on 2024-04-22 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('generic_name', models.CharField(max_length=50)),
                ('route', models.CharField(max_length=50)),
                ('outpatients', models.IntegerField(blank=True, null=True)),
                ('inpatients', models.IntegerField(blank=True, null=True)),
                ('patients', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ValueSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_id', models.CharField(max_length=100, unique=True)),
                ('value_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ValueMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_medications', to='vandyapi.medication')),
                ('valueset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_values', to='vandyapi.valueset')),
            ],
        ),
        migrations.AddField(
            model_name='medication',
            name='values',
            field=models.ManyToManyField(related_name='medications', through='vandyapi.ValueMedication', to='vandyapi.valueset'),
        ),
    ]
